language: android
dist: trusty
before_install:
- openssl aes-256-cbc -K $encrypted_f86dd6e78143_key -iv $encrypted_f86dd6e78143_iv -in android_keystore.jks.enc -out android_keystore.jks -d
- yes | sdkmanager "platforms;android-30"
android:
  components:
  - tools
  - platform-tools
  - tools
  - build-tools-30.0.3
  - android-30
  - extra-google-m2repository
  - extra-android-m2repository
notifications:
  email: false
jdk:
- oraclejdk8
script:
- export APP_VERSION=$(./gradlew -q :zero:printVersionName)
- export TRAVIS_TAG=$APP_VERSION-${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
- "./gradlew build"
deploy:
  provider: releases
  api_key:
    secure: IcKIxsnpd9xdc43XHOtsS1bxl2kJ231F2iUTXQzQJ2fsOoU1y+QpY0yYqH9bxNLN8KTLq3xAC8AZRxu1AEHh92fJiSRHHZVyPZBFVRIryVglsihqXahG97QOnaFRXBAVD9y6B2OBb5TngBJjONWAV1xX6CW9v5JrC22fKpWkdBUGrM8srOCGwc9+vKjmBlREYSJEwHcZqzsf1YcYWjYBjJTNe0Am6H8AtOivgsJuMTNj+2v4eMH9NfRd3B/ymu/ky+93pvxtAUtylETBZcKS6zSXm5h6nAa2N1eobq2JYREdrXYMSKZwaAsgGw1AtPVydyK0rhw3/ykU08yx0KqfNuhGIadWaGjuIHreSWPMQUgcKLXQaDnvFRzYfJJ2PFXaKfyLe/egfFuDwhiXSH2dGYGy9fNjPKCui+M3QgtqVoL0C/WZSoaeQqCJunL4pyQIHCkmam86Uz2guxoIWzaWpmmGsoV9rxAgOtdtDFD+9nFTmiV1rXo47aH97pBP+fqSjvX07WL8ti00v+AR/pCKOOYFFlO6GAJ/VjfhOTf9eNi6R6Nzbzpx97Dc7HxcTn5nDroLcfBaUppPdFMgjpXnJQh+QK6rJOegRbY9CmTh1Yc4Ik1DiRyD+VYFBYtKCxs96kNBdyxktBq1s4J4JEQbbhynHUwPSyQIhxAXZxc9haQ=
  skip_cleanup: true
  overwrite: true
  file_glob: true
  file: "/home/travis/build/lucasasselli/zero/zero/build/outputs/apk/release/*"
  on:
     branch: master
